"use client";

import { useEffect, useState } from "react";
import WidgetRenderer from "@/components/WidgetRenderer";
import type { WidgetSpec } from "@/types/widget";
import { fetchExamples } from "@/lib/api";
import { Loader2, ArrowRight } from "lucide-react";
import Link from "next/link";
import { motion } from "framer-motion";

export default function ExplorePage() {
  const [examples, setExamples] = useState<WidgetSpec[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeWidget, setActiveWidget] = useState<WidgetSpec | null>(null);

  useEffect(() => {
    fetchExamples()
      .then((data) => {
        setExamples(data);
        if (data.length > 0) setActiveWidget(data[0]);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  return (
    <main className="flex-1 flex flex-col items-center py-12 px-4">
      <div className="w-full max-w-6xl">
        <div className="mb-12 text-center">
          <h1 className="text-3xl font-display font-bold text-white mb-4">Explore Examples</h1>
          <p className="text-ink-muted max-w-2xl mx-auto">
            Browse through pre-built widgets generated by our AI. Click on any widget to interact with it, 
            or go to the canvas to generate your own.
          </p>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="w-8 h-8 animate-spin text-glow-graph" />
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* List */}
            <div className="lg:col-span-1 space-y-4">
              {examples.map((ex, i) => (
                <button
                  key={i}
                  onClick={() => setActiveWidget(ex)}
                  className={`w-full text-left p-4 rounded-xl border transition-all ${
                    activeWidget === ex 
                      ? "bg-canvas-panel border-glow-graph/50 shadow-[0_0_20px_-5px_rgba(34,211,238,0.3)]" 
                      : "bg-canvas border-canvas-border hover:border-ink-muted/30"
                  }`}
                >
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-xs font-mono font-medium text-ink-muted uppercase">
                      {ex.widget}
                    </span>
                  </div>
                  <p className="text-sm text-white line-clamp-2">{ex.tutor_text}</p>
                </button>
              ))}
              
              <Link href="/canvas" className="group flex items-center justify-between w-full p-4 mt-8 rounded-xl bg-white text-black font-medium transition-all hover:bg-neutral-200">
                Generate Your Own
                <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
              </Link>
            </div>

            {/* Preview */}
            <div className="lg:col-span-2">
              {activeWidget && (
                <motion.div
                  key={activeWidget.tutor_text}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-canvas-panel/50 backdrop-blur-md border border-canvas-border rounded-2xl p-6 min-h-[500px] flex items-center justify-center"
                >
                  <WidgetRenderer spec={activeWidget} />
                </motion.div>
              )}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
